var tinyMCEImageList = new Array(
['Images: articles','http://localhost/Projects/PadsanCMS/General/images/articles'],
['Images: avatars','http://localhost/Projects/PadsanCMS/General/images/avatars'],
['Images: edit.gif','http://localhost/Projects/PadsanCMS/General/images/edit.gif'],
['Images: icon-large-support.png','http://localhost/Projects/PadsanCMS/General/images/icon-large-support.png'],
['Images: imagelist.js','http://localhost/Projects/PadsanCMS/General/images/imagelist.js'],
['Images: imagenotfound.jpg','http://localhost/Projects/PadsanCMS/General/images/imagenotfound.jpg'],
['Images: news','http://localhost/Projects/PadsanCMS/General/images/news'],
['Images: news_cats','http://localhost/Projects/PadsanCMS/General/images/news_cats'],
['Images: photoalbum','http://localhost/Projects/PadsanCMS/General/images/photoalbum'],
['Images: slideshow','http://localhost/Projects/PadsanCMS/General/images/slideshow'],
['Images: star.gif','http://localhost/Projects/PadsanCMS/General/images/star.gif'],
['Images: Thumbs.db','http://localhost/Projects/PadsanCMS/General/images/Thumbs.db'],
['Images: tick.gif','http://localhost/Projects/PadsanCMS/General/images/tick.gif'],
['Images: up.gif','http://localhost/Projects/PadsanCMS/General/images/up.gif'],
['Images: validate_bg.jpg','http://localhost/Projects/PadsanCMS/General/images/validate_bg.jpg'],
['news: icon-large-support.png','http://localhost/Projects/PadsanCMS/General/images/news/icon-large-support.png'],
['news: Thumbs.db','http://localhost/Projects/PadsanCMS/General/images/news/Thumbs.db'],
[' album: album_1','http://localhost/Projects/PadsanCMS/General/images/photoalbum/album_1'],
[' album: album_2','http://localhost/Projects/PadsanCMS/General/images/photoalbum/album_2'],
[' album: Chrysanthemum.jpg','http://localhost/Projects/PadsanCMS/General/images/photoalbum/Chrysanthemum.jpg'],
[' album: submissions','http://localhost/Projects/PadsanCMS/General/images/photoalbum/submissions'],
[' album: Thumbs.db','http://localhost/Projects/PadsanCMS/General/images/photoalbum/Thumbs.db']);

